services:
  trading:
    container_name: trading
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - trading_net

  redis:
    container_name: redis
    image: public.ecr.aws/docker/library/redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - trading_net


networks:
  trading_net:
    external: True
